name = "xiongqi-hub"
main = "worker/index.ts"
compatibility_date = "2026-09-15"
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "xiongqi-hub"
database_id = "41e400b0-e91e-440e-a192-0165e5079a95"
